apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs
  template:
    metadata:
      labels:
        app: fs
    spec:
      containers:
      - name: fs
        image: fs:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: fs-service
spec:
  selector:
    app: fs
  ports:
  - port: 9090
    targetPort: 9090
  type: LoadBalancer 